apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../default-ingress/
patches:
- patch-deployment-control-plane.yaml
- patch-deployment-hostports.yaml
commonAnnotations:
  app.kubernetes.io/version: v0.46.0
replicas:
- name: ingress-nginx-controller
  count: 1
