steps:
#
# Build our python:3 based cloud-builder including kustomize
#
- name: 'gcr.io/cloud-builders/docker'
  args:
   - build
   - --build-arg
   - KUSTOMIZE_VERSION=2.0.0
   - -t
   - cloud-builder-python3-kustomize
   - .

#
# Copy from src to dist
#
- name: 'cloud-builder-python3-kustomize'
  args: ['bash', '-c', './dist.py']
  env:
  - 'PYTHONUNBUFFERED=1'
  - 'TAG_NAME=$TAG_NAME'
  - 'BRANCH_NAME=$BRANCH_NAME'
  - 'SHORT_SHA=$SHORT_SHA'

#
# Test kustomize build
#
- name: 'cloud-builder-python3-kustomize'
  args: ['bash', '-c', './test.py']
  env:
  - 'PYTHONUNBUFFERED=1'
  - 'TAG_NAME=$TAG_NAME'
  - 'BRANCH_NAME=$BRANCH_NAME'
  - 'SHORT_SHA=$SHORT_SHA'

#
# Copy from dist to bucket
#
artifacts:
  objects:
    location: 'gs://$_CATALOG_BUCKET_NAME'
    paths: ['_dist/*.zip']
