bases:
- ../base/
commonAnnotations:
  catalog.kubestack.com/heritage: kubestack.com/catalog/postgresql
  catalog.kubestack.com/variant: clusterwide
commonLabels:
  app.kubernetes.io/component: operator
  app.kubernetes.io/managed-by: kubestack
  app.kubernetes.io/name: postgresql
  app.kubernetes.io/version: v1.1.0
namespace: operator-postgresql
patchesStrategicMerge:
- patch-deployment-env.yaml
resources:
- namespace.yaml
- rbac.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
