apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: memcached-operator
rules:
- apiGroups:
  - kubestack.com
  resources:
  - memcacheds
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - list
  - create
  - get
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - list
  - get
  - delete
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - list
  - create
  - get
  - patch
  - delete
