apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base/

namespace: operator-memcached

commonAnnotations:
  catalog.kubestack.com/heritage: kubestack.com/catalog/memcached
  catalog.kubestack.com/variant: clusterwide
  app.kubernetes.io/version: v0.2.1

commonLabels:
  app.kubernetes.io/component: operator
  app.kubernetes.io/managed-by: kubestack
  app.kubernetes.io/name: memcached

resources:
- namespace.yaml
- service_account.yaml
- cluster_role.yaml
- cluster_role_binding.yaml
