apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongodb-operator
rules:
- apiGroups:
  - kubestack.com
  resources:
  - mongodbs
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - list
  - create
  - get
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - list
  - create
  - get
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - create
  - get
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - get
