apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb-operator
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: kubestack/mongodb:latest
        imagePullPolicy: Always
        name: mongodb-operator
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      serviceAccountName: mongodb-operator
