resources:
- postgres-operator.yaml
- configmap.yaml

commonLabels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: "4c8dfd7"
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: kubestack

commonAnnotations:
    catalog.kubestack.com/heritage: kubestack.com/catalog/postgresql
    catalog.kubestack.com/variant: base
