apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  catalog.kubestack.com/heritage: kubestack.com/catalog/postgresql
  catalog.kubestack.com/variant: base
commonLabels:
  app.kubernetes.io/component: operator
  app.kubernetes.io/managed-by: kubestack
  app.kubernetes.io/name: postgresql
  app.kubernetes.io/version: v1.1.0
images:
- name: registry.opensource.zalan.do/acid/smoke-tested-postgres-operator
  newName: registry.opensource.zalan.do/acid/postgres-operator
  newTag: v1.1.0
kind: Kustomization
resources:
- postgres-operator.yaml
- configmap.yaml
