apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
commonAnnotations:
  catalog.kubestack.com/heritage: kubestack.com/catalog/argo-cd
  catalog.kubestack.com/variant: ha-namespaced
  app.kubernetes.io/version: v1.8.3
  app.kubernetes.io/managed-by: kubestack
resources:
- namespace.yaml
- namespace-install.yaml
