apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: operator-etcd

bases:
- ../base/

commonAnnotations:
  catalog.kubestack.com/heritage: kubestack.com/catalog/etcd
  catalog.kubestack.com/variant: clusterwide
  app.kubernetes.io/version: v0.9.4

commonLabels:
  app.kubernetes.io/component: operator
  app.kubernetes.io/managed-by: kubestack
  app.kubernetes.io/name: etcd

patchesStrategicMerge:
- patch_deployment_command.yaml
- patch_deployment_sa_name.yaml

resources:
- cluster_role_binding.yaml
- cluster_role.yaml
- namespace.yaml
- service_account.yaml
