apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
commonAnnotations:
  catalog.kubestack.com/heritage: kubestack.com/catalog/argo-cd
  catalog.kubestack.com/variant: normal
  app.kubernetes.io/version: v1.8.2
  app.kubernetes.io/managed-by: kubestack
resources:
- namespace.yaml
- install.yaml
