apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  catalog.kubestack.com/heritage: kubestack.com/catalog/prometheus
  catalog.kubestack.com/variant: base
resources:
- bundle.yaml
