apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: operator-prometheus

commonAnnotations:
  app.kubernetes.io/version: v0.29.0
  catalog.kubestack.com/heritage: kubestack.com/catalog/prometheus
  catalog.kubestack.com/variant: clusterwide

commonLabels:
  app.kubernetes.io/component: operator
  app.kubernetes.io/managed-by: kubestack
  app.kubernetes.io/name: prometheus

resources:
- ../base/
- namespace.yaml
- instance-cluster-role.yaml
