apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch-operator
  namespace: operator-elasticsearch
spec:
  template:
      spec:
          containers:
          - name: operator
            command:
            - "/bin/sh"
            - "-c"
            - "/usr/local/bin/elasticsearch-operator -initDaemonsetNamespace=$(NAMESPACE)"
