apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: operator-mongodb

commonLabels:
  app.kubernetes.io/component: operator
  app.kubernetes.io/managed-by: kubestack
  app.kubernetes.io/name: mongodb

commonAnnotations:
  app.kubernetes.io/version: latest
  catalog.kubestack.com/heritage: kubestack.com/catalog/mongodb
  catalog.kubestack.com/variant: clusterwide

resources:
- ../base/
- namespace.yaml
- service_account.yaml
- cluster_role.yaml
- cluster_role_binding.yaml
