name: Build

on:
  push:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags

jobs:
  test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kustomize-version: ["2.0.3", "3.1.0", "3.2.3"]

    steps:
    - uses: actions/checkout@v1

    #
    #
    # Build image
    - name: Build image
      env:
        DOCKER_BUILDKIT: 1
      run: docker build --build-arg KUSTOMIZE_VERSION=${{ matrix.kustomize-version }} -t python3-kustomize:${{ matrix.kustomize-version }} .

    #
    #
    # Run dist.py
    - name: Run dist.py
      env:
          GIT_REF: ${{ github.ref }}
          GIT_SHA: ${{ github.sha }}
      run: docker run -e GIT_REF -e GIT_SHA -v /home/runner/work/catalog/catalog:/github/workspace -w /github/workspace python3-kustomize:${{ matrix.kustomize-version }} bash -c './dist.py'

    #
    #
    # Run test.py
    - name: Run test.py
      run: docker run -v /home/runner/work/catalog/catalog:/github/workspace -w /github/workspace python3-kustomize:${{ matrix.kustomize-version }} bash -c './test.py'


  upload-build:
    runs-on: ubuntu-latest
    needs: test-build

    steps:
    - uses: actions/checkout@v1

    #
    #
    # Build image
    - name: Build image
      env:
        DOCKER_BUILDKIT: 1
      run: docker build --build-arg KUSTOMIZE_VERSION=3.2.3 -t python3-kustomize:3.2.3 .

    #
    #
    # Run dist.py
    - name: Run dist.py
      env:
          GIT_REF: ${{ github.ref }}
          GIT_SHA: ${{ github.sha }}
      run: docker run -e GIT_REF -e GIT_SHA -v /home/runner/work/catalog/catalog:/github/workspace -w /github/workspace python3-kustomize:3.2.3 bash -c './dist.py'

    #
    #
    # Upload archive
    - uses: actions/gcloud/auth@master
      name: Auth
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}

    - uses: actions/gcloud/cli@master
      name: Upload
      with:
        entrypoint: /builder/google-cloud-sdk/bin/gsutil
        args: -m cp _dist/*.zip gs://dev.catalog.kubestack.com
