name: Build

on:
  push:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    #
    #
    # Run builder
    - name: Run updater
      uses: ./.github/actions/builder

    #
    #
    # Upload artifacts
    - name: 'Upload artifacts'
      uses: actions/upload-artifact@v2
      with:
        name: _dist
        path: _dist

  test-kustomize:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kustomize-version: ["3.2.3", "3.5.4", "3.8.1"]
    needs: build

    steps:
    - uses: actions/checkout@v1

    #
    #
    # Download build artifacts
    - name: 'Download build-artifacts'
      uses: actions/download-artifact@v2
      with:
        name: _dist
        path: _dist

    #
    #
    # Build image
    - name: Build image
      env:
        DOCKER_BUILDKIT: 1
      run: docker build --build-arg KUSTOMIZE_VERSION=${{ matrix.kustomize-version }} -t python3-kustomize:${{ matrix.kustomize-version }} .

    #
    #
    # Run test.py
    - name: Run test.py
      run: docker run -v /home/runner/work/catalog/catalog:/github/workspace -w /github/workspace python3-kustomize:${{ matrix.kustomize-version }} bash -c './test.py'


  publish:
    runs-on: ubuntu-latest
    needs: test-kustomize

    steps:
    #
    #
    # Download build artifacts
    - name: 'Download build-artifacts'
      uses: actions/download-artifact@v2
      with:
        name: _dist
        path: _dist

    #
    #
    # Upload archive
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCLOUD_AUTH }}

    - run: gsutil -m cp _dist/*.zip gs://dev.catalog.kubestack.com
