name: Promote
run-name: 'Promote :: ${{ github.ref }}'

on: workflow_dispatch

jobs:
  #
  #
  # Promote tagged releases
  # from `dev.catalog.kubestack.com` to `catalog.kubestack.com`
  promote:
    runs-on: ubuntu-latest

    # promote only for tags
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    # Setup gcloud CLI
    - uses: google-github-actions/auth@v1.1.1
      with:
        credentials_json: '${{ secrets.GCLOUD_AUTH }}'

    - uses: google-github-actions/setup-gcloud@v1.1.1

    # Promote archive
    - run: |
            export TAG=$(echo $GITHUB_REF | sed -e "s#^refs/tags/##")
            export NAME=$(echo $TAG | sed -r 's#-v[0-9]+.*$##')
            set +e
            while true
            do
                gsutil cp gs://dev.catalog.kubestack.com/module-${NAME}-${GITHUB_SHA}.zip gs://catalog.kubestack.com/module-${TAG}.zip &&\
                break
                sleep 15
            done

    # Check promotion
    - name: Check promotion
      run: |
            export TAG=$(echo $GITHUB_REF | sed -e "s#^refs/tags/##")
            wget https://storage.googleapis.com/catalog.kubestack.com/module-${TAG}.zip
