name: Release

on:
  push:
    branches:
    - "!*"  # do not run on any branches
    tags:
    - "*"  # only run for tags

jobs:
  test-deploy:
    runs-on: ubuntu-latest

    steps:
    #
    #
    # Setup Kind
    - uses: engineerd/setup-kind@v0.3.0

    #
    #
    # Extract archive
    - name: Extract archive
      run: |
            export NAME=$(echo $GITHUB_REF | sed -e "s#^refs/tags/##")
            set +e
            while true
            do
                wget https://storage.googleapis.com/dev.catalog.kubestack.com/${NAME}.zip && break
                sleep 15
            done
            mkdir -p _test
            unzip -d _test/ ${NAME}.zip

    #
    #
    # Get binaries
    - name: Get binaries
      env:
          TERRAFORM_VERSION: 0.12.24
          TERRAFORM_PROVIDER_KUSTOMIZE_VERSION: v0.1.0-beta.3
      run: |
        echo "TERRAFORM_VERSION: ${TERRAFORM_VERSION}"
        curl -LO https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
        unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /opt/bin
        chmod +x /opt/bin/terraform
        /opt/bin/terraform version
        rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip
        echo
        echo
        echo "TERRAFORM_PROVIDER_KUSTOMIZE_VERSION: ${TERRAFORM_PROVIDER_KUSTOMIZE_VERSION}"
        mkdir -p terraform.d/plugins/linux_amd64
        curl -LO https://github.com/kbst/terraform-provider-kustomize/releases/download/${TERRAFORM_PROVIDER_KUSTOMIZE_VERSION}/terraform-provider-kustomization-${TERRAFORM_PROVIDER_KUSTOMIZE_VERSION}-linux-amd64
        mv terraform-provider-kustomization-${TERRAFORM_PROVIDER_KUSTOMIZE_VERSION}-linux-amd64 terraform.d/plugins/linux_amd64/terraform-provider-kustomization
        chmod +x terraform.d/plugins/linux_amd64/terraform-provider-kustomization

    #
    #
    # Write test.tf.tpl
    # data "kustomization" "test" {
    #   # path to kustomization directory
    #   path = ""
    # }
    #
    # resource "kustomization_resource" "test" {
    #   for_each = data.kustomization.test.ids
    #
    #   manifest = data.kustomization.test.manifests[each.value]
    # }
    - name: Write test.tf.tpl
      run: |
        echo "ZGF0YSAia3VzdG9taXphdGlvbiIgInRlc3QiIHsKICAjIHBhdGggdG8ga3VzdG9taXphdGlvbiBkaXJlY3RvcnkKICBwYXRoID0gIiIKfQoKcmVzb3VyY2UgImt1c3RvbWl6YXRpb25fcmVzb3VyY2UiICJ0ZXN0IiB7CiAgZm9yX2VhY2ggPSBkYXRhLmt1c3RvbWl6YXRpb24udGVzdC5pZHMKCiAgbWFuaWZlc3QgPSBkYXRhLmt1c3RvbWl6YXRpb24udGVzdC5tYW5pZmVzdHNbZWFjaC52YWx1ZV0KfQo=" | base64 --decode > test.tf.tpl

    #
    #
    # Deploy to cluster
    - name: Deploy
      run: |
            export PATH=$PATH:/opt/bin

            kubectl version
            kubectl cluster-info

            for entry in $(ls _test/)
            do
                for overlay in $(ls _test/$entry)
                do
                    sed 's#path = ""#path = "_test/'${entry}'/'${overlay}'"#g' test.tf.tpl > test.tf

                    terraform init

                    echo && echo '### TEST APPLY ###'
                    terraform apply --auto-approve

                    echo && echo '### TEST READY ###'
                    kubectl wait pod --for=condition=Ready --timeout=300s --all --all-namespaces

                    echo && echo '### TEST DELETE ###'
                    terraform destroy --auto-approve
                done
            done

  promote:
    runs-on: ubuntu-latest

    needs: test-deploy

    steps:
    #
    #
    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCLOUD_AUTH }}

    #
    #
    # Promote archive
    - run: |
            export NAME=$(echo $GITHUB_REF | sed -e "s#^refs/tags/##")
            set +e
            while true
            do
                gsutil cp gs://dev.catalog.kubestack.com/${NAME}.zip gs://catalog.kubestack.com/${NAME}.zip && break
                sleep 15
            done

    #
    #
    # Check promotion
    - name: Check promotion
      run: |
            export NAME=$(echo $GITHUB_REF | sed -e "s#^refs/tags/##")
            wget https://storage.googleapis.com/catalog.kubestack.com/${NAME}.zip
