name: Update

on:
  schedule:
    - cron:  "0 6 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    #
    #
    # Run updater
    - name: Run updater
      uses: ./.github/actions/updater
